import json, re
from pathlib import Path
p=Path('/mnt/data/v34work/lib/data.ts')
s=p.read_text()

def ex(en, ja, focus, obj=None, jaFocus=None):
    d={'en':en,'ja':ja,'focus':focus}
    if obj: d['object']=obj
    if jaFocus: d['jaFocus']=jaFocus
    return d

def meaning(i, mid, title, pattern, struct, image, point, examples, daily):
    return {'id':mid,'title':f'{i} {title}','pattern':pattern,'transitivity':'他動詞・自動詞','structure':struct,'image':image,'point':point,'examples':examples,'dailyExamples':daily}

def phrase(ph, ja, pattern, examples, daily):
    return {'phrase':ph,'ja':ja,'image':f'{ph} は仕事で「{ja}」場面に使いやすい表現です。','pattern':pattern,'examples':examples,'dailyExamples':daily}

def make_phrases(items):
    out=[]
    for ph,ja in items:
        out.append(phrase(ph,ja,ph.upper()+' + ...',[
            ex(f'I will {ph} this today.',f'今日これを{ja}します。',ph,'this',ja),
            ex(f'We need to {ph} it before the meeting.',f'会議前にそれを{ja}する必要があります。',ph,'it',ja),
            ex(f'Please {ph} the details with the team.',f'詳細をチームと{ja}してください。',ph,'the details',ja)
        ],[
            ex(f'I often {ph} this at home.',f'家でよくこれを{ja}します。',ph,'this',ja),
            ex(f'It helps to {ph} in daily life.',f'日常生活で{ja}できると役立ちます。',ph,None,ja)
        ]))
    return out

def verb_obj(id, rank, word, ipa, kana, core, detail, visual_from, meanings, collocs, phrasals):
    return {
      'id':id,'rank':rank,'word':word,'ipa':ipa,'kana':kana,'syllable':id,
      'transitivity':'他動詞・自動詞','importance':'★★★★☆ 重要','core':core,'coreDetail':detail,
      'coreVisual':{'from':visual_from,'to':'仕事の流れ','label':'コアイメージ'},
      'meanings':meanings,'collocations':make_phrases(collocs),'phrasalVerbs':make_phrases(phrasals)
    }

start=verb_obj('start',21,'START','/stɑːrt/','スタート','止まっているものを動き出させる','STARTは会議・作業・案件・習慣など、まだ動いていないものを動き出させる感覚です。仕事では会議開始、業務開始、プロジェクト開始で頻出します。',['▶️ 開始','📅 予定','📊 案件','💬 会議','⚙️ 作業'],[
 meaning(1,'begin','始める','START + 名詞','S + V + O','会議や作業を始める。','start の後ろに始める対象を置きます。meeting, project, task などとよく使います。',[ex("Let's start the meeting.",'会議を始めましょう。','start','the meeting','始め'),ex('We need to start the project next week.','来週その案件を始める必要があります。','start','the project','始める'),ex('Please start the report today.','今日レポートを始めてください。','start','the report','始めて')],[ex('I started a new habit this month.','今月新しい習慣を始めました。','started','a new habit','始めました'),ex('She started learning English again.','彼女は英語学習を再開しました。','started','learning English','再開しました')]),
 meaning(2,'begin-intransitive','始まる','START','S + V','イベントや会議が始まる。','自動詞として「始まる」。時間表現と相性が良いです。',[ex('The meeting starts at ten.','会議は10時に始まります。','starts',None,'始まります'),ex('The training starts next Monday.','研修は来週月曜日に始まります。','starts',None,'始まります'),ex('The campaign started yesterday.','キャンペーンは昨日始まりました。','started',None,'始まりました')],[ex('The movie starts at seven.','映画は7時に始まります。','starts',None,'始まります'),ex('School starts in April.','学校は4月に始まります。','starts',None,'始まります')]),
 meaning(3,'launch','開始する・立ち上げる','START + 企画 / 事業','S + V + O','企画や事業を立ち上げる。','launchより日常的に使える基本表現です。',[ex('We started a new service for clients.','顧客向けの新サービスを開始しました。','started','a new service','開始しました'),ex('The company started a new branch in Osaka.','会社は大阪に新しい支店を立ち上げました。','started','a new branch','立ち上げました'),ex('They started a new sales campaign.','彼らは新しい営業キャンペーンを開始しました。','started','a new sales campaign','開始しました')],[ex('I started a small blog.','小さなブログを始めました。','started','a small blog','始めました'),ex('He started a side project.','彼は副業プロジェクトを始めました。','started','a side project','始めました')]),
 meaning(4,'cause','〜させ始める','START + O + 動詞ing','S + V + O + C','何かを動き始めさせる。','start the system running のように「開始状態にする」感覚です。',[ex('The update started the system running again.','更新でシステムが再び動き始めました。','started','the system','動き始めました'),ex('The announcement started a discussion.','その発表で議論が始まりました。','started','a discussion','始まりました'),ex('The issue started a review process.','その問題をきっかけに見直しが始まりました。','started','a review process','始まりました')],[ex('The news started a conversation.','そのニュースで会話が始まりました。','started','a conversation','始まりました'),ex('The rain started people running.','雨で人々が走り始めました。','started','people','走り始めました')]),
 meaning(5,'restart','再開する','START + again / over','S + V','一度止まったものを再び始める。','start again / start over はやり直しで便利です。',[ex('Let us start again from the main issue.','主要な問題からもう一度始めましょう。','start',None,'始め'),ex('We started over after the system error.','システムエラー後にやり直しました。','started over',None,'やり直しました'),ex('Can we start the discussion again?','議論を再開できますか？','start','the discussion','再開')],[ex('I want to start over this year.','今年やり直したいです。','start over',None,'やり直したい'),ex('She started again after a break.','彼女は休憩後に再開しました。','started',None,'再開しました')]),
 meaning(6,'start-work','仕事を始める','START work / START at 会社','S + V + O','勤務や仕事を始める。','start work は仕事開始、start at は勤務先開始。',[ex('I start work at nine.','私は9時に仕事を始めます。','start','work','仕事を始め'),ex('She started at our company last month.','彼女は先月当社で働き始めました。','started',None,'働き始めました'),ex('He will start his new role next week.','彼は来週新しい役職を始めます。','start','his new role','始めます')],[ex('I started a new job in April.','4月に新しい仕事を始めました。','started','a new job','始めました'),ex('My day starts with coffee.','私の1日はコーヒーで始まります。','starts',None,'始まります')]),
 meaning(7,'start-from','〜から始める','START from + 起点','S + V + 前置詞句','起点を示して始める。','説明や確認の出だしに便利です。',[ex('Let us start from the budget.','予算から始めましょう。','start',None,'始めましょう'),ex('We should start from the customer needs.','顧客ニーズから始めるべきです。','start',None,'始める'),ex('The process starts from this form.','手続きはこのフォームから始まります。','starts',None,'始まります')],[ex('I started from zero.','ゼロから始めました。','started',None,'始めました'),ex('The trip starts from Tokyo.','旅行は東京から始まります。','starts',None,'始まります')]),
 meaning(8,'start-with','〜で始める','START with + 名詞','S + V + 前置詞句','最初の内容を示す。','会議や説明の流れ作りに便利。',[ex('Let us start with the sales numbers.','売上数字から始めましょう。','start',None,'始めましょう'),ex('I will start with a quick summary.','簡単な要約から始めます。','start',None,'始めます'),ex('The report starts with the market overview.','報告書は市場概要から始まります。','starts',None,'始まります')],[ex('I start with easy exercises.','簡単な練習から始めます。','start',None,'始めます'),ex('Dinner started with soup.','夕食はスープから始まりました。','started',None,'始まりました')]),
 meaning(9,'start-time','開始時刻になる','START at + 時刻','S + V + 前置詞句','始まる時間を示す。','予定調整で頻出。',[ex('The call starts at three.','電話会議は3時に始まります。','starts',None,'始まります'),ex('The seminar starts at one p.m.','セミナーは午後1時に始まります。','starts',None,'始まります'),ex('What time does the meeting start?','会議は何時に始まりますか？','start',None,'始まります')],[ex('The concert starts at six.','コンサートは6時に始まります。','starts',None,'始まります'),ex('The lesson starts soon.','レッスンはまもなく始まります。','starts',None,'始まります')]),
 meaning(10,'start-small','小さく始める','START small','S + V + C','小さな規模で始める。','社会人の学習や事業で使いやすい表現。',[ex('We should start small and improve later.','小さく始めて後で改善すべきです。','start',None,'小さく始め'),ex('The team started small with one client.','チームは1社の顧客から小さく始めました。','started',None,'小さく始めました'),ex('Let us start small to reduce risk.','リスクを減らすため小さく始めましょう。','start',None,'小さく始め')],[ex('I started small with five minutes a day.','1日5分から小さく始めました。','started',None,'小さく始めました'),ex('Start small if you feel busy.','忙しいなら小さく始めましょう。','Start',None,'小さく始め')])
],[('start a meeting','会議を始める'),('start a project','案件を始める'),('start work','仕事を始める'),('start a report','報告書を始める'),('start a discussion','議論を始める'),('start a service','サービスを開始する'),('start a campaign','キャンペーンを開始する'),('start a review','見直しを始める'),('start from zero','ゼロから始める'),('start small','小さく始める')],[('start over','やり直す'),('start up','立ち上げる'),('start off','始める'),('start out','出発する'),('start with','〜から始める'),('start from','〜から始める'),('start on','取り掛かる'),('start back','戻り始める'),('start in','始める'),('start after','〜の後に始める')])

show=verb_obj('show',25,'SHOW','/ʃoʊ/','ショウ','相手に見える形にする','SHOWは「見せる」だけでなく、資料・数字・結果・態度を相手に分かる形で示す感覚です。仕事では説明、提示、証明に使います。',['👁️ 見える','📊 数字','📄 資料','✅ 結果','💬 説明'],[
 meaning(1,'display','見せる・表示する','SHOW + 名詞','S + V + O','資料や情報を相手に見せる。','show someone something / show something to someone の形で使います。',[ex("I'll show you the data.",'データをお見せします。','show','the data','お見せ'),ex('Please show the latest report to the client.','最新レポートを顧客に見せてください。','show','the latest report','見せて'),ex('The dashboard shows current progress.','ダッシュボードは現在の進捗を表示しています。','shows','current progress','表示しています')],[ex('Can you show me the photo?','写真を見せてもらえますか？','show','the photo','見せて'),ex('The app shows my daily progress.','アプリは毎日の進捗を表示します。','shows','my daily progress','表示します')]),
 meaning(2,'explain','説明する','SHOW + 人 + how to','S + V + O + C','やり方を見せて説明する。','show how to は実演説明に便利。',[ex('Can you show me how to use this system?','このシステムの使い方を教えてもらえますか？','show','me','教えて'),ex('I will show the team how to update the file.','チームにファイル更新方法を説明します。','show','the team','説明します'),ex('Please show new members how to submit reports.','新メンバーに報告書の提出方法を教えてください。','show','new members','教えて')],[ex('She showed me how to cook it.','彼女が作り方を教えてくれました。','showed','me','教えて'),ex('Can you show me how this works?','これがどう動くか教えてくれますか？','show','me','教えて')]),
 meaning(3,'indicate','示す','SHOW + 結果 / 傾向','S + V + O','数字や事実が何かを示す。','data shows that... はビジネス頻出。',[ex('The data shows a clear trend.','データは明確な傾向を示しています。','shows','a clear trend','示しています'),ex('The survey shows customer satisfaction is improving.','調査は顧客満足度が改善していることを示しています。','shows','customer satisfaction is improving','示しています'),ex('The results show we need more support.','結果は追加サポートが必要だと示しています。','show','we need more support','示しています')],[ex('The map shows the nearest station.','地図は最寄り駅を示しています。','shows','the nearest station','示しています'),ex('His face showed surprise.','彼の顔は驚きを示していました。','showed','surprise','示していました')]),
 meaning(4,'prove','証明する','SHOW that + 文','S + V + O','事実や結果で証明する。','show は prove より柔らかく「示す」。',[ex('This report shows that the plan is working.','この報告書は計画が機能していることを示しています。','shows','that the plan is working','示しています'),ex('The numbers show that sales are increasing.','数字は売上が伸びていることを示しています。','show','that sales are increasing','示しています'),ex('The test showed that the issue was fixed.','テストで問題が修正されたことが分かりました。','showed','that the issue was fixed','分かりました')],[ex('The results showed that he was right.','結果は彼が正しいことを示しました。','showed','that he was right','示しました'),ex('The weather shows that spring is coming.','天気を見ると春が近づいていると分かります。','shows','that spring is coming','分かります')]),
 meaning(5,'show-up','現れる・出席する','SHOW UP','S + V','人が現れる・参加する。','会議や約束に来る意味。',[ex('He did not show up for the meeting.','彼は会議に現れませんでした。','show up',None,'現れませんでした'),ex('Please show up five minutes early.','5分早く来てください。','show up',None,'来て'),ex('Only three people showed up to the training.','研修には3人しか参加しませんでした。','showed up',None,'参加しませんでした')],[ex('My friend showed up late.','友人は遅れて来ました。','showed up',None,'来ました'),ex('I showed up at the wrong place.','間違った場所に行ってしまいました。','showed up',None,'行って')]),
 meaning(6,'show-interest','態度を見せる','SHOW + 感情 / 態度','S + V + O','気持ちや態度を表す。','show interest / concern は仕事で自然。',[ex('The client showed interest in our product.','顧客は当社製品に関心を示しました。','showed','interest','関心を示しました'),ex('Management showed concern about the delay.','経営陣は遅延に懸念を示しました。','showed','concern','懸念を示しました'),ex('The team showed strong commitment.','チームは強い責任感を示しました。','showed','strong commitment','示しました')],[ex('She showed kindness to everyone.','彼女は皆に親切さを示しました。','showed','kindness','示しました'),ex('He showed no interest in the movie.','彼はその映画に関心を示しませんでした。','showed','no interest','示しませんでした')]),
 meaning(7,'show-around','案内する','SHOW + 人 + around','S + V + O + C','場所を案内する。','show someone around は来客対応に便利。',[ex('I will show the visitor around the office.','来客にオフィスを案内します。','show','the visitor','案内します'),ex('Can you show the client around the showroom?','顧客にショールームを案内してもらえますか？','show','the client','案内して'),ex('She showed us around the factory.','彼女が工場を案内してくれました。','showed','us','案内して')],[ex('I showed my friend around Tokyo.','友人に東京を案内しました。','showed','my friend','案内しました'),ex('Can you show me around this area?','この辺りを案内してくれますか？','show','me','案内して')]),
 meaning(8,'show-in','通す・案内する','SHOW + 人 + in','S + V + O + C','人を中へ案内する。','受付や来客対応に使う。',[ex('Please show the client in.','顧客を中へご案内してください。','show','the client','案内して'),ex('The receptionist showed us in.','受付の方が私たちを中へ案内してくれました。','showed','us','案内して'),ex('Can you show the guest into the meeting room?','ゲストを会議室へ案内できますか？','show','the guest','案内できますか')],[ex('She showed me into the living room.','彼女は私をリビングへ案内しました。','showed','me','案内しました'),ex('The staff showed us in.','スタッフが私たちを中へ案内しました。','showed','us','案内しました')]),
 meaning(9,'show-on-screen','画面に出る','SHOW on + 画面','S + V + 前置詞句','画面や資料に表示される。','エラーやデータ表示に便利。',[ex('The error message shows on the screen.','エラーメッセージが画面に表示されます。','shows',None,'表示されます'),ex('The total price shows at the bottom.','合計金額は下部に表示されます。','shows',None,'表示されます'),ex('The status shows as pending.','ステータスは保留中と表示されています。','shows',None,'表示されています')],[ex('My name did not show on the list.','私の名前はリストに表示されませんでした。','show',None,'表示されませんでした'),ex('The photo shows clearly on my phone.','写真はスマホではっきり表示されます。','shows',None,'表示されます')]),
 meaning(10,'show-respect','示す','SHOW + respect/support','S + V + O','敬意や支援を示す。','抽象名詞とも相性が良い。',[ex('We should show respect to our partners.','取引先に敬意を示すべきです。','show','respect','示す'),ex('The manager showed support for the proposal.','マネージャーは提案への支持を示しました。','showed','support','示しました'),ex('Please show appreciation to the team.','チームに感謝を示してください。','show','appreciation','示して')],[ex('I want to show my thanks.','感謝を示したいです。','show','my thanks','示したい'),ex('He showed respect to his parents.','彼は両親に敬意を示しました。','showed','respect','示しました')])
],[('show data','データを見せる'),('show results','結果を示す'),('show interest','関心を示す'),('show concern','懸念を示す'),('show support','支持を示す'),('show respect','敬意を示す'),('show progress','進捗を示す'),('show a trend','傾向を示す'),('show a client around','顧客を案内する'),('show appreciation','感謝を示す')],[('show up','現れる'),('show around','案内する'),('show in','中へ案内する'),('show out','外へ案内する'),('show off','見せびらかす'),('show through','透けて見える'),('show over','案内して回る'),('show to','〜に見せる'),('show on','表示される'),('show as','〜として表示される')])

openv=verb_obj('open',36,'OPEN','/ˈoʊpən/','オープン','閉じているものを使える状態にする','OPENは物理的に開く以外に、会議・ファイル・可能性・議論を使える状態にする感覚です。',['🔓 開く','📄 ファイル','💬 議論','🚪 機会','📅 会議'],[
 meaning(1,'open-file','開く','OPEN + 名詞','S + V + O','ファイルや資料を開く。','open the file は仕事で最頻出。',[ex('Please open the file I sent you.','送ったファイルを開いてください。','open','the file','開いて'),ex('I opened the latest report.','最新レポートを開きました。','opened','the latest report','開きました'),ex('Can you open the attachment?','添付ファイルを開けますか？','open','the attachment','開けますか')],[ex('I opened the app on my phone.','スマホでアプリを開きました。','opened','the app','開きました'),ex('Open the window, please.','窓を開けてください。','Open','the window','開けて')]),
 meaning(2,'start-meeting','会議を始める','OPEN + 会議','S + V + O','会議を開始する。','open a meeting はややフォーマル。',[ex('The manager opened the meeting with a short update.','マネージャーは短い報告で会議を始めました。','opened','the meeting','始めました'),ex('Let me open today\'s meeting.','本日の会議を始めさせてください。','open','today\'s meeting','始め'),ex('She opened the session with a greeting.','彼女は挨拶でセッションを始めました。','opened','the session','始めました')],[ex('The event opened with music.','イベントは音楽で始まりました。','opened',None,'始まりました'),ex('The ceremony opened at ten.','式典は10時に始まりました。','opened',None,'始まりました')]),
 meaning(3,'make-available','利用可能にする','OPEN + 機会 / アクセス','S + V + O','アクセスや機会を開く。','open access / open opportunities のように使う。',[ex('This update opens new opportunities.','この更新は新しい機会を生みます。','opens','new opportunities','生みます'),ex('The new system opens access to shared data.','新システムで共有データにアクセスできるようになります。','opens','access','アクセスできるように'),ex('The partnership opened a new market.','提携により新しい市場が開けました。','opened','a new market','開けました')],[ex('Studying English opens many doors.','英語学習は多くの可能性を広げます。','opens','many doors','広げます'),ex('The ticket opened the gate.','チケットでゲートが開きました。','opened','the gate','開きました')]),
 meaning(4,'discuss','話を切り出す','OPEN + discussion','S + V + O','議論を始める。','open a discussion は会議で自然。',[ex('I would like to open the discussion.','議論を始めたいと思います。','open','the discussion','始め'),ex('This issue opens an important discussion.','この問題は重要な議論につながります。','opens','an important discussion','つながります'),ex('Can we open the topic of pricing?','価格の話題を始めてもいいですか？','open','the topic','始め')],[ex('I opened a conversation with my neighbor.','近所の人と会話を始めました。','opened','a conversation','始めました'),ex('She opened the topic carefully.','彼女はその話題を慎重に切り出しました。','opened','the topic','切り出しました')]),
 meaning(5,'become-open','開く・営業する','OPEN','S + V','店やサービスが開く。','自動詞で使う。',[ex('The office opens at nine.','オフィスは9時に開きます。','opens',None,'開きます'),ex('The registration opens next Monday.','登録は来週月曜に始まります。','opens',None,'始まります'),ex('The support desk opens at ten.','サポート窓口は10時に開きます。','opens',None,'開きます')],[ex('The shop opens early.','その店は早く開きます。','opens',None,'開きます'),ex('The park opens in spring.','公園は春に開園します。','opens',None,'開園します')]),
 meaning(6,'open-account','口座・アカウントを開設する','OPEN + account','S + V + O','アカウントや口座を作る。','open an account は定型。',[ex('We opened a new account for the client.','顧客用に新しいアカウントを開設しました。','opened','a new account','開設しました'),ex('Please open a user account for him.','彼用のユーザーアカウントを作成してください。','open','a user account','作成して'),ex('The company opened a bank account overseas.','会社は海外で銀行口座を開設しました。','opened','a bank account','開設しました')],[ex('I opened a savings account.','貯蓄口座を開設しました。','opened','a savings account','開設しました'),ex('She opened a new email account.','彼女は新しいメールアカウントを作りました。','opened','a new email account','作りました')]),
 meaning(7,'open-position','募集を出す','OPEN + position','S + V + O','求人や枠を開く。','open a position は採用文脈で使う。',[ex('We opened a new sales position.','新しい営業職の募集を開始しました。','opened','a new sales position','募集を開始しました'),ex('The HR team opened three roles.','人事チームは3つの職種を募集開始しました。','opened','three roles','募集開始しました'),ex('This role will open next quarter.','この役職は来四半期に募集開始されます。','open',None,'募集開始されます')],[ex('A seat opened near the window.','窓際の席が空きました。','opened',None,'空きました'),ex('A spot opened in the class.','クラスに空きが出ました。','opened',None,'空きが出ました')]),
 meaning(8,'open-up','打ち明ける・広げる','OPEN UP','S + V','心や可能性が開く。','ビジネスでは市場や機会にも使える。',[ex('The new channel opened up more sales opportunities.','新しい販路で販売機会が広がりました。','opened up','more sales opportunities','広がりました'),ex('The manager opened up about the challenge.','マネージャーは課題について率直に話しました。','opened up',None,'率直に話しました'),ex('AI opened up new ways to work.','AIにより新しい働き方が広がりました。','opened up','new ways to work','広がりました')],[ex('He opened up to his friend.','彼は友人に心を開きました。','opened up',None,'心を開きました'),ex('Travel opened up my mind.','旅行で視野が広がりました。','opened up','my mind','広がりました')]),
 meaning(9,'open-door','扉を開く','OPEN + door','S + V + O','物理・比喩の扉を開く。','open the door to は可能性を開く。',[ex('This contract opens the door to future business.','この契約は将来の取引につながります。','opens','the door','つながります'),ex('The meeting opened the door to cooperation.','その会議で協力の可能性が開けました。','opened','the door','可能性が開けました'),ex('Good communication opens the door to trust.','良いコミュニケーションは信頼につながります。','opens','the door','つながります')],[ex('Can you open the door?','ドアを開けてくれますか？','open','the door','開けて'),ex('Music opened the door to English for me.','音楽が私に英語への扉を開いてくれました。','opened','the door','扉を開いて')]),
 meaning(10,'open-mind','心を開く','OPEN + mind','S + V + O','考え方を柔軟にする。','open your mind は自己啓発寄り。',[ex('The training opened my mind to new ideas.','研修で新しい考え方に目が開かれました。','opened','my mind','目が開かれました'),ex('Working abroad opened my mind.','海外勤務で視野が広がりました。','opened','my mind','視野が広がりました'),ex('The feedback opened our minds to customer needs.','フィードバックで顧客ニーズに目が向きました。','opened','our minds','目が向きました')],[ex('Reading opens your mind.','読書は視野を広げます。','opens','your mind','広げます'),ex('Meeting new people opened my mind.','新しい人との出会いで視野が広がりました。','opened','my mind','広がりました')])
],[('open a file','ファイルを開く'),('open a meeting','会議を始める'),('open a discussion','議論を始める'),('open an account','アカウントを開設する'),('open access','アクセスを開く'),('open a new market','新市場を開拓する'),('open a position','募集を開始する'),('open opportunities','機会を広げる'),('open the door','可能性を開く'),('open a session','セッションを始める')],[('open up','広げる・打ち明ける'),('open out','広がる'),('open into','〜へ通じる'),('open onto','〜に面している'),('open for','〜向けに開く'),('open with','〜で始める'),('open to','〜に開かれている'),('open around','周囲に広がる'),('open back','再び開く'),('open over','広がる')])

close=verb_obj('close',37,'CLOSE','/kloʊz/','クローズ','開いているものを終わらせる・締める','CLOSEは扉を閉じるだけでなく、会議・案件・取引・期間を終える感覚です。仕事では締切、終了、成約でよく使います。',['🔒 閉じる','✅ 完了','📄 案件','🤝 成約','⏱️ 締切'],[
 meaning(1,'shut','閉じる','CLOSE + 名詞','S + V + O','扉やファイルを閉じる。','基本の「閉じる」。',[ex('Please close the file after checking it.','確認後にファイルを閉じてください。','close','the file','閉じて'),ex('I closed the document by mistake.','誤って資料を閉じました。','closed','the document','閉じました'),ex('Close the browser before the update.','更新前にブラウザを閉じてください。','Close','the browser','閉じて')],[ex('Please close the window.','窓を閉めてください。','close','the window','閉めて'),ex('I closed the door quietly.','静かにドアを閉めました。','closed','the door','閉めました')]),
 meaning(2,'finish','終える','CLOSE + 会議 / セッション','S + V + O','会議や話を締める。','close a meeting はフォーマルに使える。',[ex('Let us close the meeting here.','ここで会議を終えましょう。','close','the meeting','終え'),ex('The chair closed the session at five.','議長は5時にセッションを終了しました。','closed','the session','終了しました'),ex('I will close this discussion with one point.','最後に1点述べてこの議論を締めます。','close','this discussion','締めます')],[ex('The event closed with a speech.','イベントはスピーチで終わりました。','closed',None,'終わりました'),ex('The ceremony closed peacefully.','式典は無事に終わりました。','closed',None,'終わりました')]),
 meaning(3,'deal','成約する','CLOSE + deal / sale','S + V + O','商談や契約をまとめる。','営業で非常に重要。',[ex('We closed the deal yesterday.','昨日その取引を成約しました。','closed','the deal','成約しました'),ex('The sales team closed a major contract.','営業チームは大きな契約をまとめました。','closed','a major contract','まとめました'),ex('She closed the sale after the presentation.','彼女はプレゼン後に販売を成立させました。','closed','the sale','成立させました')],[ex('He finally closed the deal for his car.','彼はついに車の取引をまとめました。','closed','the deal','まとめました'),ex('They closed the agreement last night.','彼らは昨夜合意をまとめました。','closed','the agreement','まとめました')]),
 meaning(4,'end-period','終了する','CLOSE','S + V','期間や受付が終わる。','registration closes など。',[ex('Registration closes this Friday.','登録は今週金曜日に締め切られます。','closes',None,'締め切られます'),ex('The application period closes tomorrow.','申込期間は明日終了します。','closes',None,'終了します'),ex('The office closes at six.','オフィスは6時に閉まります。','closes',None,'閉まります')],[ex('The shop closes at nine.','その店は9時に閉まります。','closes',None,'閉まります'),ex('The park closes in winter.','その公園は冬に閉園します。','closes',None,'閉園します')]),
 meaning(5,'close-gap','差を縮める','CLOSE + gap','S + V + O','差や距離を小さくする。','close the gap はビジネス・学習で便利。',[ex('We need to close the gap between plan and result.','計画と実績の差を縮める必要があります。','close','the gap','縮める'),ex('The team closed the performance gap.','チームは成果の差を縮めました。','closed','the performance gap','縮めました'),ex('Training helps close the skill gap.','研修はスキル差を埋めるのに役立ちます。','close','the skill gap','埋める')],[ex('Practice closes the gap little by little.','練習で少しずつ差が縮まります。','closes','the gap','縮まります'),ex('They closed the distance between them.','彼らは距離を縮めました。','closed','the distance','縮めました')]),
 meaning(6,'close-case','完了処理する','CLOSE + case / ticket','S + V + O','対応を完了にする。','サポートや管理で使う。',[ex('Please close the support ticket.','サポートチケットを完了にしてください。','close','the support ticket','完了に'),ex('We closed the issue after testing.','テスト後に問題をクローズしました。','closed','the issue','クローズしました'),ex('Can I close this case now?','この件を完了にしてもよいですか？','close','this case','完了に')],[ex('I closed the task on my list.','リスト上のタスクを完了にしました。','closed','the task','完了にしました'),ex('She closed the app after use.','使用後にアプリを閉じました。','closed','the app','閉じました')]),
 meaning(7,'be-near','近い','CLOSE to + 名詞','S + V + C','距離や関係が近い。','形容詞 close として重要。',[ex('Our office is close to the station.','弊社オフィスは駅に近いです。','is close',None,'近い'),ex('The deadline is close.','締切が近いです。','is close',None,'近い'),ex('We are close to an agreement.','合意に近づいています。','are close',None,'近づいて')],[ex('My house is close to the park.','家は公園に近いです。','is close',None,'近い'),ex('We are close friends.','私たちは親しい友人です。','are close',None,'親しい')]),
 meaning(8,'close-to','〜しそうになる','CLOSE to + 動詞ing','S + V + C','ほぼその状態に近い。','close to finishing など。',[ex('We are close to finishing the report.','報告書の完成に近づいています。','are close',None,'近づいて'),ex('The team is close to solving the issue.','チームは問題解決に近づいています。','is close',None,'近づいて'),ex('We are close to reaching the target.','目標達成に近づいています。','are close',None,'近づいて')],[ex('I was close to giving up.','諦めそうになりました。','was close',None,'諦めそう'),ex('She is close to finishing the book.','彼女は本を読み終えそうです。','is close',None,'読み終えそう')]),
 meaning(9,'close-down','閉鎖する','CLOSE DOWN','S + V','事業や店を閉じる。','close down は完全閉鎖。',[ex('The old branch closed down last year.','旧支店は昨年閉鎖されました。','closed down',None,'閉鎖されました'),ex('They closed down the service after the merger.','合併後にそのサービスを終了しました。','closed down','the service','終了しました'),ex('The factory may close down next month.','工場は来月閉鎖される可能性があります。','close down',None,'閉鎖される')],[ex('The restaurant closed down suddenly.','そのレストランは突然閉店しました。','closed down',None,'閉店しました'),ex('The website closed down.','そのウェブサイトは閉鎖されました。','closed down',None,'閉鎖されました')]),
 meaning(10,'close-out','締める・終える','CLOSE OUT + 名詞','S + V + O','会計や案件を締める。','close out は終了処理に便利。',[ex('We need to close out this project.','この案件を完了処理する必要があります。','close out','this project','完了処理する'),ex('Please close out the monthly report.','月次レポートを締めてください。','close out','the monthly report','締めて'),ex('The team closed out the quarter successfully.','チームは四半期を無事に締めました。','closed out','the quarter','締めました')],[ex('I closed out my old account.','古いアカウントを解約しました。','closed out','my old account','解約しました'),ex('The store closed out the sale.','店はセールを終了しました。','closed out','the sale','終了しました')])
],[('close a deal','取引をまとめる'),('close a meeting','会議を終える'),('close a file','ファイルを閉じる'),('close a case','案件を完了する'),('close the gap','差を縮める'),('close the sale','販売を成立させる'),('close registration','登録を締め切る'),('close the issue','問題を完了にする'),('close the office','オフィスを閉める'),('close the discussion','議論を締める')],[('close down','閉鎖する'),('close out','締める'),('close in','迫る'),('close off','封鎖する'),('close up','閉める'),('close on','迫る'),('close over','覆う'),('close around','囲む'),('close with','〜で締める'),('close to','〜に近い')])

let=verb_obj('let',51,'LET','/let/','レット','相手や物事をそのまま通す・許す','LETは自分が止めずに相手の行動や状態を許す感覚です。仕事では「〜させる」「任せる」「知らせる」で非常によく使います。',['✅ 許可','👤 相手','💬 連絡','➡️ 通す','🤝 任せる'],[
 meaning(1,'allow','許可する・〜させる','LET + 人 + 動詞原形','S + V + O + C','相手が行動できるようにする。','let me know / let us start など、日常・仕事で非常に多い。',[ex('Please let me know your schedule.','ご都合をお知らせください。','let','me','お知らせ'),ex('Let me check the details.','詳細を確認させてください。','Let','me','確認させて'),ex('We will let the client review the draft.','クライアントに草案を確認してもらいます。','let','the client','確認してもらいます')],[ex('Let me help you.','手伝わせてください。','Let','me','手伝わせて'),ex('My parents let me travel alone.','両親は一人旅を許してくれました。','let','me','許して')]),
 meaning(2,'inform','知らせる','LET + 人 + know','S + V + O + C','相手に情報を入れる。','let me know はビジネス最重要フレーズ。',[ex('Please let me know if you have any questions.','ご質問があればお知らせください。','let','me','お知らせ'),ex('I will let you know once it is ready.','準備ができたらお知らせします。','let','you','お知らせ'),ex('Could you let us know the delivery date?','納品日をお知らせいただけますか？','let','us','お知らせ')],[ex('Let me know when you arrive.','着いたら知らせてください。','Let','me','知らせて'),ex('I will let you know later.','後で知らせます。','let','you','知らせます')]),
 meaning(3,'suggest','〜しましょう','LET us + 動詞','S + V + O + C','一緒に行動を始める提案。','let us は丁寧、let\'s は自然。',[ex("Let's start with the main issue.",'主要な問題から始めましょう。',"Let's",None,'始めましょう'),ex("Let's review the numbers first.",'まず数字を確認しましょう。',"Let's",None,'確認しましょう'),ex("Let's move to the next topic.",'次の議題に移りましょう。',"Let's",None,'移りましょう')],[ex("Let's go home.",'帰りましょう。',"Let's",None,'帰りましょう'),ex("Let's have lunch together.",'一緒に昼食を食べましょう。',"Let's",None,'食べましょう')]),
 meaning(4,'release','離す・解放する','LET + O + go','S + V + O + C','保持していたものを手放す。','let go は感情や人にも使う。',[ex('We had to let the old process go.','古いやり方を手放す必要がありました。','let','the old process','手放す'),ex('The company let several temporary workers go.','会社は複数の臨時社員を契約終了にしました。','let','several temporary workers','契約終了に'),ex('It is hard to let this idea go.','このアイデアを手放すのは難しいです。','let','this idea','手放す')],[ex('Let it go.','気にしないで。','Let','it','気にしない'),ex('She let the bird go.','彼女は鳥を逃がしました。','let','the bird','逃がしました')]),
 meaning(5,'let-in','入れる','LET + 人 + in','S + V + O + C','人を中へ入れる。','来客や会議参加に使える。',[ex('Please let the visitor in.','来客を中へ入れてください。','let','the visitor','入れて'),ex('Can you let me into the online meeting?','オンライン会議に入れてもらえますか？','let','me','入れて'),ex('The admin let us into the system.','管理者が私たちをシステムに入れてくれました。','let','us','入れて')],[ex('Please let me in.','中に入れてください。','let','me','入れて'),ex('He let the dog in.','彼は犬を中に入れました。','let','the dog','入れました')]),
 meaning(6,'let-out','外へ出す・漏らす','LET + O + out','S + V + O + C','中にあるものを外へ出す。','情報漏れにも注意。',[ex('Do not let confidential information out.','機密情報を外に漏らさないでください。','let','confidential information','漏らさない'),ex('The report let out some important details.','その報告書で重要な詳細が外に出ました。','let out','some important details','外に出ました'),ex('Please let the team out after the session.','セッション後にチームを退出させてください。','let','the team','退出させて')],[ex('She let out a sigh.','彼女はため息をつきました。','let out','a sigh','つきました'),ex('Let the cat out.','猫を外へ出して。','Let','the cat','出して')]),
 meaning(7,'let-down','失望させる','LET + 人 + down','S + V + O + C','期待を下げてしまう。','let someone down は謝罪表現にも使える。',[ex('I am sorry to let you down.','期待に応えられず申し訳ありません。','let','you','応えられず'),ex('We cannot let the client down.','顧客を失望させるわけにはいきません。','let','the client','失望させる'),ex('The delay let the team down.','遅延はチームを落胆させました。','let','the team','落胆させました')],[ex('Please do not let me down.','がっかりさせないでください。','let','me','がっかりさせない'),ex('I felt I let my family down.','家族をがっかりさせた気がしました。','let','my family','がっかりさせた')]),
 meaning(8,'let-through','通す','LET + O + through','S + V + O + C','人や物を通過させる。','承認フローや入口で使える。',[ex('Security let us through after checking our IDs.','警備員は身分証確認後、私たちを通してくれました。','let','us','通して'),ex('The system will not let this request through.','システムはこの依頼を通しません。','let','this request','通しません'),ex('Please let the urgent order through first.','急ぎの注文を先に通してください。','let','the urgent order','通して')],[ex('The gate let us through.','ゲートを通過できました。','let','us','通過できました'),ex('They let the car through.','彼らは車を通しました。','let','the car','通しました')]),
 meaning(9,'let-use','使わせる','LET + 人 + use','S + V + O + C','相手が使えるように許す。','会議室・資料・システム使用に便利。',[ex('Can you let me use this room?','この部屋を使わせてもらえますか？','let','me','使わせて'),ex('The manager let us use the sample data.','マネージャーはサンプルデータの使用を許可してくれました。','let','us','使用を許可して'),ex('Please let the new staff use the shared account.','新しいスタッフに共有アカウントを使わせてください。','let','the new staff','使わせて')],[ex('My friend let me use his bike.','友人が自転車を使わせてくれました。','let','me','使わせて'),ex('She let me borrow her book.','彼女は本を貸してくれました。','let','me','貸して')]),
 meaning(10,'let-happen','そのままにする','LET + O + happen / be','S + V + O + C','止めずに起こらせる。','let it be / let it happen の感覚。',[ex('We should not let this issue happen again.','この問題を再発させてはいけません。','let','this issue','再発させて'),ex('Do not let small mistakes grow.','小さなミスを大きくしないでください。','let','small mistakes','大きくしない'),ex('Let the process continue for now.','ひとまず手続きを続けましょう。','Let','the process','続けましょう')],[ex('Let it be for now.','今はそのままにしておきましょう。','Let','it','そのまま'),ex('Sometimes you need to let things happen.','時には物事を自然に任せる必要があります。','let','things','任せる')])
],[('let me know','知らせてください'),('let me check','確認させてください'),('let us start','始めましょう'),('let the client review','顧客に確認してもらう'),('let someone use','使わせる'),('let the team know','チームに知らせる'),('let it go','手放す'),('let it happen','そのまま起こらせる'),('let someone in','中へ入れる'),('let someone down','失望させる')],[('let in','中へ入れる'),('let out','外へ出す'),('let down','失望させる'),('let through','通す'),('let go','手放す'),('let on','漏らす'),('let off','免除する'),('let up','弱まる'),('let into','中へ入れる'),('let alone','まして〜ない')])

objs={'start':start,'show':show,'open':openv,'close':close,'let':let}

def find_obj(text,idv):
    pat=f'\n  {{\n    "id": "{idv}"'
    m=re.search(re.escape(pat), text)
    if not m: return None
    start=m.start()+1
    depth=0; in_str=False; esc=False
    for i,ch in enumerate(text[start:], start):
        if in_str:
            if esc: esc=False
            elif ch=='\\': esc=True
            elif ch=='"': in_str=False
        else:
            if ch=='"': in_str=True
            elif ch=='{': depth+=1
            elif ch=='}':
                depth-=1
                if depth==0:
                    end=i+1
                    if end < len(text) and text[end]==',': end+=1
                    return start,end
    return None

for idv,obj in objs.items():
    loc=find_obj(s,idv)
    txt='  '+json.dumps(obj,ensure_ascii=False,indent=4).replace('\n','\n  ')+','
    if loc:
        s=s[:loc[0]]+txt+s[loc[1]:]
    else:
        # insert before build if possible, otherwise before array end
        loc2=find_obj(s,'build')
        if loc2:
            s=s[:loc2[0]]+txt+'\n'+s[loc2[0]:]
        else:
            s=s.replace('\n];\n\nexport const testItems', '\n'+txt+'\n];\n\nexport const testItems')

p.write_text(s)
print('v34 verbs updated')
