from pathlib import Path
p=Path('/mnt/data/v73work/lib/data.ts')
s=p.read_text()
verbs = [
('adjust',101,'ADJUST','/əˈdʒʌst/','アジャスト','ad-just','他動詞・自動詞','予定・数値・方法をちょうどよく直す','調整する','ADJUST THE SCHEDULE','予定・数値・方法を状況に合わせて直す','We adjusted the delivery schedule for the client.','私たちはクライアント向けに納品スケジュールを調整しました。','I adjusted the brightness on my phone.','私はスマホの明るさを調整しました。','adjust the schedule','スケジュールを調整する','Please adjust the schedule by Friday.','金曜日までにスケジュールを調整してください。'),
('apply',102,'APPLY','/əˈplaɪ/','アプライ','ap-ply','他動詞・自動詞','ルール・知識・申請を目的に向けて使う','申し込む・適用する','APPLY FOR A JOB / APPLY A RULE','目的に向けて申請する、またはルールや知識を使う','I applied for a new position last week.','私は先週、新しい職種に応募しました。','You can apply this idea to daily life.','この考え方は日常生活にも応用できます。','apply for approval','承認を申請する','We need to apply for approval before ordering.','私たちは発注前に承認を申請する必要があります。'),
('approve',103,'APPROVE','/əˈpruːv/','アプルーブ','ap-prove','他動詞','内容を確認して正式に認める','承認する','APPROVE A REQUEST','依頼・見積・計画を確認して正式に認める','My manager approved the quotation this morning.','私の上司は今朝、その見積を承認しました。','My parents approved my travel plan.','両親は私の旅行計画を認めてくれました。','approve the request','依頼を承認する','The client approved the request yesterday.','クライアントは昨日、その依頼を承認しました。'),
('borrow',104,'BORROW','/ˈbɑːroʊ/','ボロー','bor-row','他動詞','一時的に相手から借りて使う','借りる','BORROW A TOOL','相手の物やお金を一時的に借りる','Can I borrow your charger during the meeting?','会議中にあなたの充電器を借りてもいいですか。','I borrowed a book from the library.','私は図書館で本を借りました。','borrow money','お金を借りる','We should not borrow money without a clear plan.','私たちは明確な計画なしにお金を借りるべきではありません。'),
('check',105,'CHECK','/tʃek/','チェック','check','他動詞・自動詞','間違いがないか確認する','確認する','CHECK THE DETAILS','内容・状態・予定を確認する','Please check the details before we send the email.','メールを送る前に詳細を確認してください。','I checked the weather before leaving home.','私は家を出る前に天気を確認しました。','check with someone','人に確認する','I will check with the supplier and reply today.','私は仕入先に確認して本日返信します。'),
('collect',106,'COLLECT','/kəˈlekt/','コレクト','col-lect','他動詞','必要なものを集めて一か所にまとめる','集める','COLLECT INFORMATION','情報・資料・お金などを集める','We collected customer feedback after the event.','私たちはイベント後に顧客の意見を集めました。','My son collects toy cars.','私の息子はミニカーを集めています。','collect data','データを集める','We need to collect data before making a proposal.','私たちは提案前にデータを集める必要があります。'),
('communicate',107,'COMMUNICATE','/kəˈmjuːnɪkeɪt/','コミュニケイト','com-mu-ni-cate','自動詞・他動詞','考えや情報を相手に伝えて共有する','伝える・連絡を取る','COMMUNICATE WITH CLIENTS','相手と情報や考えをやり取りする','We communicate with the client mainly by email.','私たちは主にメールでクライアントと連絡を取っています。','I want to communicate better in English.','私は英語でもっと上手に意思疎通したいです。','communicate clearly','明確に伝える','Please communicate the deadline clearly to the team.','締切をチームに明確に伝えてください。'),
('describe',108,'DESCRIBE','/dɪˈskraɪb/','ディスクライブ','de-scribe','他動詞','特徴や状況を言葉で説明する','説明する・描写する','DESCRIBE THE SITUATION','状況・特徴・問題を言葉で説明する','Could you describe the problem in more detail?','その問題をもう少し詳しく説明していただけますか。','She described the restaurant very well.','彼女はそのレストランをとても上手に説明しました。','describe a product','製品を説明する','We need to describe the product benefits clearly.','私たちは製品の利点を明確に説明する必要があります。'),
('earn',109,'EARN','/ɜːrn/','アーン','earn','他動詞','努力の結果としてお金・信頼・評価を得る','稼ぐ・得る','EARN MONEY / EARN TRUST','努力によってお金・信頼・評価を得る','Our team earned the client’s trust through quick support.','私たちのチームは迅速な対応でクライアントの信頼を得ました。','He earns money by teaching guitar.','彼はギターを教えてお金を稼いでいます。','earn trust','信頼を得る','Good service helps us earn trust.','良いサービスは私たちが信頼を得る助けになります。'),
('estimate',110,'ESTIMATE','/ˈestɪmeɪt/','エスティメイト','es-ti-mate','他動詞','費用・数量・時間をおおよそ計算する','見積もる','ESTIMATE THE COST','費用・時間・数量をおおよそ計算する','We estimated the installation cost yesterday.','私たちは昨日、設置費用を見積もりました。','I estimated the travel time before leaving.','私は出発前に移動時間を見積もりました。','estimate the delivery time','納期を見積もる','Can you estimate the delivery time for this order?','この注文の納期を見積もっていただけますか。'),
('focus',111,'FOCUS','/ˈfoʊkəs/','フォーカス','fo-cus','自動詞・他動詞','注意や力を一点に向ける','集中する','FOCUS ON A TASK','注意や力を一つの対象に向ける','We should focus on the most urgent issue first.','私たちはまず最も緊急の問題に集中すべきです。','I focus better in a quiet room.','私は静かな部屋の方が集中できます。','focus on quality','品質に集中する','Our team focuses on quality and speed.','私たちのチームは品質とスピードに注力しています。'),
('identify',112,'IDENTIFY','/aɪˈdentɪfaɪ/','アイデンティファイ','i-den-ti-fy','他動詞','多くの中から問題・原因・対象を特定する','特定する','IDENTIFY THE PROBLEM','問題・原因・対象を見つけて特定する','We identified the cause of the delay.','私たちは遅延の原因を特定しました。','Can you identify this bird?','この鳥が何か分かりますか。','identify a risk','リスクを特定する','We need to identify the risk before starting.','私たちは開始前にリスクを特定する必要があります。'),
('introduce',113,'INTRODUCE','/ˌɪntrəˈduːs/','イントロデュース','in-tro-duce','他動詞','人・物・仕組みを初めて相手に示す','紹介する・導入する','INTRODUCE A NEW SYSTEM','人を紹介する、または新しい仕組みを導入する','We introduced a new system to reduce mistakes.','私たちはミスを減らすために新しいシステムを導入しました。','Please introduce yourself to the group.','グループに自己紹介してください。','introduce a product','製品を紹介する','I introduced our new product to the client.','私はクライアントに新製品を紹介しました。'),
('join',114,'JOIN','/dʒɔɪn/','ジョイン','join','他動詞・自動詞','人や活動の輪に加わる','参加する・加わる','JOIN A MEETING','会議・活動・グループに加わる','I will join the online meeting at three.','私は3時にオンライン会議に参加します。','My daughter joined a dance class.','娘はダンス教室に参加しました。','join a project','プロジェクトに参加する','She joined the project last month.','彼女は先月そのプロジェクトに参加しました。'),
('lead',115,'LEAD','/liːd/','リード','lead','他動詞・自動詞','人や仕事を前に進める方向へ導く','導く・率いる','LEAD A TEAM','人・チーム・案件を前に進める','He led the project from start to finish.','彼は最初から最後までそのプロジェクトを率いました。','This road leads to the station.','この道は駅へ続いています。','lead a meeting','会議を進行する','Can you lead the meeting tomorrow?','明日の会議を進行してもらえますか。'),
('maintain',116,'MAINTAIN','/meɪnˈteɪn/','メインテイン','main-tain','他動詞','良い状態を保ち続ける','維持する','MAINTAIN QUALITY','品質・関係・状態を保ち続ける','We maintain quality by checking every product.','私たちはすべての製品を確認することで品質を維持しています。','I try to maintain a healthy routine.','私は健康的な習慣を維持しようとしています。','maintain a relationship','関係を維持する','Regular communication helps maintain a good relationship.','定期的な連絡は良い関係を維持する助けになります。'),
('mention',117,'MENTION','/ˈmenʃn/','メンション','men-tion','他動詞','話の中で短く触れる','言及する','MENTION A POINT','話・メール・会議で短く触れる','I mentioned the delivery issue in my email.','私はメールで納期の問題に言及しました。','She mentioned a good cafe near the station.','彼女は駅近くの良いカフェについて少し話しました。','mention a deadline','締切に言及する','Please mention the deadline in the proposal.','提案書で締切に言及してください。'),
('protect',118,'PROTECT','/prəˈtekt/','プロテクト','pro-tect','他動詞','大切なものを危険や損失から守る','守る・保護する','PROTECT DATA','人・物・情報を危険から守る','We must protect customer data carefully.','私たちは顧客データを慎重に保護しなければなりません。','Sunscreen protects your skin.','日焼け止めは肌を守ります。','protect privacy','プライバシーを守る','This setting helps protect user privacy.','この設定はユーザーのプライバシーを守る助けになります。'),
('replace',119,'REPLACE','/rɪˈpleɪs/','リプレイス','re-place','他動詞','古いものを新しいものに入れ替える','交換する・置き換える','REPLACE AN OLD PART','古いもの・壊れたものを新しいものに入れ替える','We replaced the damaged LED module.','私たちは破損したLEDモジュールを交換しました。','I replaced my old phone last year.','私は昨年、古いスマホを買い替えました。','replace A with B','AをBに置き換える','We replaced the old system with a new one.','私たちは古いシステムを新しいものに置き換えました。'),
('train',120,'TRAIN','/treɪn/','トレイン','train','他動詞・自動詞','練習や指導でできるようにする','訓練する・研修する','TRAIN NEW STAFF','人を指導してできるようにする','We trained new staff on the product basics.','私たちは新しいスタッフに製品の基本を研修しました。','I train at the gym twice a week.','私は週2回ジムでトレーニングしています。','train a team','チームを育成する','The manager trained the team carefully.','そのマネージャーはチームを丁寧に育成しました。'),
]

def obj(v):
    id,rank,word,ipa,kana,syll,trans,core,title,pattern,image,biz_en,biz_ja,daily_en,daily_ja,phrase,phrase_ja,phrase_en,phrase_ja_ex=v
    return f''',\n{{\n  "id": "{id}",\n  "rank": {rank},\n  "word": "{word}",\n  "ipa": "{ipa}",\n  "kana": "{kana}",\n  "syllable": "{syll}",\n  "transitivity": "{trans}",\n  "importance": "★★★★☆ 重要",\n  "core": "{core}",\n  "coreDetail": "{word}は、社会人の仕事でも日常会話でも使いやすい基本動詞です。まずは「{title}」の感覚で、よく使う目的語や前置詞との組み合わせを覚えると会話で使いやすくなります。",\n  "meanings": [\n    {{\n      "id": "m1",\n      "title": "① {title}",\n      "pattern": "{pattern}",\n      "transitivity": "{trans}",\n      "structure": "S + V + O / 必要に応じて前置詞句",\n      "image": "{image}",\n      "point": "{id} は、後ろに目的語や前置詞句を置いて、仕事・日常の具体的な行動を表します。",\n      "examples": [\n        {{\n          "en": "{biz_en}",\n          "ja": "{biz_ja}",\n          "focus": "{id}",\n          "jaFocus": "{title}",\n          "sentencePattern": "S + V + O",\n          "grammarParts": [\n            {{ "label": "S", "text": "主語" }},\n            {{ "label": "V", "text": "{id}" }},\n            {{ "label": "O", "text": "目的語・内容" }}\n          ],\n          "grammarNote": "初心者向けには、まず主語・動詞・目的語の流れで理解します。前置詞句は補足情報として扱います。"\n        }},\n        {{\n          "en": "{daily_en}",\n          "ja": "{daily_ja}",\n          "focus": "{id}",\n          "jaFocus": "{title}"\n        }}\n      ]\n    }}\n  ],\n  "collocations": [\n    {{\n      "phrase": "{phrase}",\n      "ja": "{phrase_ja}",\n      "image": "{image}",\n      "pattern": "{phrase.upper()}",\n      "examples": [\n        {{\n          "en": "{phrase_en}",\n          "ja": "{phrase_ja_ex}",\n          "focus": "{phrase}",\n          "jaFocus": "{phrase_ja}"\n        }}\n      ]\n    }}\n  ],\n  "phrasalVerbs": []\n}}'''
insert=''.join(obj(v) for v in verbs)
s=s.replace('\n];\n\n\nconst dailyMeaningExamples', insert+'\n];\n\n\nconst dailyMeaningExamples')
p.write_text(s)
