from pathlib import Path
p=Path('/mnt/data/v57work/components/InstantTest.tsx')
s=p.read_text()
s=s.replace('''import { clearTestSession, getTestSession, recordReviewResult, recordSectionClear, recordTestResult, recordVerbMastery, saveTestSession } from "@/lib/account";''','''import { clearTestSession, getCurrentProgress, getTestSession, recordReviewResult, recordSectionClear, recordTestResult, recordVerbMastery, saveProgress, saveTestSession, type UserProgress } from "@/lib/account";''')
insert='''\ntype TestSnapshot = {\n  index: number;\n  shown: boolean;\n  correct: number;\n  wrong: number;\n  progress: UserProgress | null;\n};\n\nfunction cloneProgress(progress: UserProgress | null): UserProgress | null {\n  return progress ? JSON.parse(JSON.stringify(progress)) : null;\n}\n\nfunction shuffleItems(items: TestItem[]) {\n  return [...items]\n    .map((item) => ({ item, sort: Math.random() }))\n    .sort((a, b) => a.sort - b.sort)\n    .map((entry) => entry.item);\n}\n\nfunction balancedTen(items: TestItem[]) {\n  if (items.length <= 10) return shuffleItems(items);\n  const groups: Record<string, TestItem[]> = { basic: [], idioms: [], phrasal: [] };\n  for (const item of shuffleItems(items)) groups[item.section].push(item);\n  const selected: TestItem[] = [];\n  for (const section of ["basic", "idioms", "phrasal"] as const) {\n    selected.push(...groups[section].splice(0, section === "basic" ? 4 : 3));\n  }\n  const used = new Set(selected.map((item) => item.id));\n  const rest = shuffleItems(items).filter((item) => !used.has(item.id));\n  return [...selected, ...rest].slice(0, 10);\n}\n'''
s=s.replace('''function sectionName(section: TestSection) {''', insert+'\nfunction sectionName(section: TestSection) {')
# replace items useMemo block
old='''  const items = useMemo<TestItem[]>(() => {\n    if (itemIds && itemIds.length > 0) {\n      return itemIds.map((id) => getTestItemById(id)).filter(Boolean) as TestItem[];\n    }\n    return getTestItemsForVerb(verbId, section);\n  }, [itemIds, verbId, section]);\n\n  const verb = getVerb(items[0]?.verbId || verbId);'''
new='''  const baseItems = useMemo<TestItem[]>(() => {\n    if (itemIds && itemIds.length > 0) {\n      return itemIds.map((id) => getTestItemById(id)).filter(Boolean) as TestItem[];\n    }\n    return getTestItemsForVerb(verbId, section);\n  }, [itemIds, verbId, section]);\n\n  const [items, setItems] = useState<TestItem[]>([]);\n  const verb = getVerb(baseItems[0]?.verbId || verbId);'''
s=s.replace(old,new)
s=s.replace('''  const [resumed, setResumed] = useState(false);\n  const item = items[index];''','''  const [resumed, setResumed] = useState(false);\n  const [history, setHistory] = useState<TestSnapshot[]>([]);\n  const item = items[index];''')
# replace load effect
old='''  useEffect(() => {\n    if (items.length === 0) return;\n    const saved = getTestSession(sessionKey);\n    if (saved && saved.itemIds.join("|") === items.map((i) => i.id).join("|")) {\n      setIndex(Math.min(saved.index, items.length));\n      setShown(saved.shown);\n      setCorrect(saved.correct);\n      setWrong(saved.wrong);\n      setResumed(saved.index > 0 || saved.correct > 0 || saved.wrong > 0);\n    } else {\n      setIndex(0);\n      setShown(false);\n      setCorrect(0);\n      setWrong(0);\n      setResumed(false);\n    }\n    setLoadedSession(true);\n  }, [items, sessionKey]);'''
new='''  useEffect(() => {\n    if (baseItems.length === 0) return;\n    const saved = getTestSession(sessionKey);\n    const savedItems = saved?.itemIds\n      .map((id) => getTestItemById(id))\n      .filter(Boolean) as TestItem[] | undefined;\n    const nextItems = savedItems && savedItems.length > 0 ? savedItems : balancedTen(baseItems);\n    setItems(nextItems);\n    if (saved && savedItems && savedItems.length > 0) {\n      setIndex(Math.min(saved.index, nextItems.length));\n      setShown(saved.shown);\n      setCorrect(saved.correct);\n      setWrong(saved.wrong);\n      setResumed(saved.index > 0 || saved.correct > 0 || saved.wrong > 0);\n    } else {\n      setIndex(0);\n      setShown(false);\n      setCorrect(0);\n      setWrong(0);\n      setResumed(false);\n    }\n    setHistory([]);\n    setLoadedSession(true);\n  }, [baseItems, sessionKey]);'''
s=s.replace(old,new)
s=s.replace('''  const restart = () => {\n    clearTestSession(sessionKey);\n    setIndex(0);\n    setShown(false);\n    setCorrect(0);\n    setWrong(0);\n    setRewardShown(false);\n    setResumed(false);\n  };''','''  const restart = () => {\n    clearTestSession(sessionKey);\n    setItems(balancedTen(baseItems));\n    setIndex(0);\n    setShown(false);\n    setCorrect(0);\n    setWrong(0);\n    setRewardShown(false);\n    setResumed(false);\n    setHistory([]);\n  };''')
s=s.replace('''  const mark = (isCorrect: boolean) => {\n    reviewMode ? recordReviewResult(item.verbId, item.id, isCorrect) : recordTestResult(item.verbId, item.id, isCorrect);\n    if (isCorrect) {\n      setCorrect((n) => n + 1);\n      next();\n    } else {\n      setWrong((n) => n + 1);\n      setShown(false);\n    }\n  };''','''  const mark = (isCorrect: boolean) => {\n    setHistory((list) => [\n      ...list,\n      { index, shown, correct, wrong, progress: cloneProgress(getCurrentProgress()) },\n    ].slice(-5));\n    reviewMode ? recordReviewResult(item.verbId, item.id, isCorrect) : recordTestResult(item.verbId, item.id, isCorrect);\n    if (isCorrect) {\n      setCorrect((n) => n + 1);\n      next();\n    } else {\n      setWrong((n) => n + 1);\n      setShown(false);\n    }\n  };\n\n  const undoLast = () => {\n    const last = history[history.length - 1];\n    if (!last) return;\n    if (last.progress) saveProgress(last.progress);\n    setIndex(last.index);\n    setShown(last.shown);\n    setCorrect(last.correct);\n    setWrong(last.wrong);\n    setHistory((list) => list.slice(0, -1));\n  };''')
# Add audio button on question screen
s=s.replace('''              <p className="mt-3 text-xs text-slate-400">下線の数だけ英単語を入れて考えます。</p>\n            </div>\n            <button className="btn btn-primary w-full" onClick={() => setShown(true)}>答えを見る</button>''','''              <p className="mt-3 text-xs text-slate-400">下線の数だけ英単語を入れて考えます。</p>\n            </div>\n            <div className="rounded-2xl border border-cyan-300/20 bg-slate-950/50 p-4">\n              <p className="mb-3 text-sm font-bold text-cyan-100">リスニング確認</p>\n              <SpeakButton text={item.en} label="英文を聞く" slowLabel="ゆっくり" lang="en-US" />\n            </div>\n            <button className="btn btn-primary w-full" onClick={() => setShown(true)}>答えを見る</button>''')
# Add undo button under answer actions and score perhaps
s=s.replace('''            <button onClick={next} className="btn btn-soft w-full">スキップして次へ</button>''','''            <button onClick={next} className="btn btn-soft w-full">スキップして次へ</button>\n            {history.length > 0 && (\n              <button onClick={undoLast} className="btn btn-soft w-full">1つ前の回答に戻る</button>\n            )}''')
# Add total random 10 note in header maybe
s=s.replace('''        <p className="mt-2 text-muted">{description || "日本語を見て、すぐ英語で言ってから答えを確認します。"}</p>''','''        <p className="mt-2 text-muted">{description || "日本語を見て、すぐ英語で言ってから答えを確認します。"}</p>\n        <p className="mt-2 text-sm font-bold text-cyan-100">出題はランダム10問です。基本・熟語・句動詞がなるべく偏らないように出ます。</p>''')
p.write_text(s)
