from pathlib import Path
p=Path('/mnt/data/v57work/lib/data.ts')
s=p.read_text()
s=s.replace('''export type Example = {\n  en: string;\n  ja: string;\n  focus?: string;\n  object?: string;\n  jaFocus?: string;\n};''','''export type GrammarPart = {\n  label: "S" | "V" | "O" | "C" | "M";\n  text: string;\n};\n\nexport type Example = {\n  en: string;\n  ja: string;\n  focus?: string;\n  object?: string;\n  jaFocus?: string;\n  sentencePattern?: string;\n  grammarParts?: GrammarPart[];\n  grammarNote?: string;\n};''')
# Direct data fixes
repls={
'''"en": "Do you get what I mean?",\n            "ja": "私の言いたいことは分かりますか？",\n            "focus": "get",\n            "jaFocus": "分かりますか"''': '''"en": "Do you get what I mean?",\n            "ja": "あなたは私の言いたいことが分かりますか？",\n            "focus": "get",\n            "object": "what I mean",\n            "jaFocus": "分かりますか",\n            "sentencePattern": "S + V + O",\n            "grammarParts": [\n              { "label": "S", "text": "you" },\n              { "label": "V", "text": "get" },\n              { "label": "O", "text": "what I mean" }\n            ],\n            "grammarNote": "Do は疑問文を作る助動詞です。what I mean が get の目的語です。"''',
'''"en": "We need to get approval before ordering.",\n            "ja": "発注前に承認を得る必要があります.",''': '''"en": "We need to get approval before ordering.",\n            "ja": "私たちは発注前に承認を得る必要があります.",''',
'''"en": "We need to get approval before ordering.",\n            "ja": "発注前に承認を得る必要があります。",''': '''"en": "We need to get approval before ordering.",\n            "ja": "私たちは発注前に承認を得る必要があります。",''',
'''"en": "We got an opportunity to work with a new client.",\n            "ja": "新しい顧客と仕事をする機会を得ました。",''': '''"en": "We got an opportunity to work with a new client.",\n            "ja": "私たちは新しい顧客と仕事をする機会を得ました。",''',
'''"en": "Can we get new samples by Friday?",\n            "ja": "金曜日までに新しいサンプルを入手できますか？",''': '''"en": "Can we get new samples by Friday?",\n            "ja": "私たちは金曜日までに新しいサンプルを入手できますか？",''',
'''"en": "I'll get Tanaka to check the document.",\n            "ja": "田中さんに資料を確認してもらいます。",\n            "focus": "get",\n            "jaFocus": "確認してもらいます"''': '''"en": "I'll get Tanaka to check the document.",\n            "ja": "私は田中さんに資料を確認してもらいます。",\n            "focus": "get",\n            "object": "Tanaka",\n            "jaFocus": "確認してもらいます",\n            "sentencePattern": "S + V + O + C",\n            "grammarParts": [\n              { "label": "S", "text": "I" },\n              { "label": "V", "text": "get" },\n              { "label": "O", "text": "Tanaka" },\n              { "label": "C", "text": "to check the document" }\n            ],\n            "grammarNote": "get + 人 + to do は「人に〜してもらう」という型です。"''',
'''"en": "Can you get the supplier to send the samples?",\n            "ja": "仕入先にサンプルを送ってもらえますか？",\n            "focus": "get",\n            "jaFocus": "送ってもらえますか"''': '''"en": "Can you get the supplier to send the samples?",\n            "ja": "あなたは仕入先にサンプルを送ってもらえますか？",\n            "focus": "get",\n            "object": "the supplier",\n            "jaFocus": "送ってもらえますか",\n            "sentencePattern": "S + V + O + C",\n            "grammarParts": [\n              { "label": "S", "text": "you" },\n              { "label": "V", "text": "get" },\n              { "label": "O", "text": "the supplier" },\n              { "label": "C", "text": "to send the samples" }\n            ],\n            "grammarNote": "Can は疑問文を作る助動詞です。the supplier が O、to send the samples が O の動きを説明します。"''',
'''"en": "We need to get the team to agree on this.",\n            "ja": "チームにこの件で合意してもらう必要があります。",\n            "focus": "get",\n            "jaFocus": "合意してもらう"''': '''"en": "We need to get the team to agree on this.",\n            "ja": "私たちはチームにこの件で合意してもらう必要があります。",\n            "focus": "get",\n            "object": "the team",\n            "jaFocus": "合意してもらう",\n            "sentencePattern": "S + V + O + C",\n            "grammarParts": [\n              { "label": "S", "text": "We" },\n              { "label": "V", "text": "get" },\n              { "label": "O", "text": "the team" },\n              { "label": "C", "text": "to agree on this" }\n            ],\n            "grammarNote": "to agree on this は the team がする動きを表します。この文では get + 人 + to do の型です。"''',
'''"en": "Let's get ready for the client meeting.",\n            "ja": "クライアントとの会議の準備をしましょう。",\n            "focus": "get ready",\n            "jaFocus": "準備"''': '''"en": "Let's get ready for the client meeting.",\n            "ja": "クライアントとの会議の準備をしましょう。",\n            "focus": "get ready",\n            "jaFocus": "準備",\n            "sentencePattern": "S + V + C + M",\n            "grammarParts": [\n              { "label": "S", "text": "we" },\n              { "label": "V", "text": "get" },\n              { "label": "C", "text": "ready" },\n              { "label": "M", "text": "for the client meeting" }\n            ],\n            "grammarNote": "Let's は Let us の短縮で「〜しましょう」。for だけでなく for the client meeting をまとまりで見ます。"''',
'''"en": "I'm getting ready for the presentation.",\n            "ja": "プレゼンの準備をしています。",\n            "focus": "getting ready",\n            "jaFocus": "準備"''': '''"en": "I'm getting ready for the presentation.",\n            "ja": "私はプレゼンの準備をしています。",\n            "focus": "getting ready",\n            "jaFocus": "準備",\n            "sentencePattern": "S + V + C + M",\n            "grammarParts": [\n              { "label": "S", "text": "I" },\n              { "label": "V", "text": "am getting" },\n              { "label": "C", "text": "ready" },\n              { "label": "M", "text": "for the presentation" }\n            ]''',
'''"en": "Let's get started.",\n            "ja": "始めましょう。",\n            "focus": "get started",\n            "jaFocus": "始め"''': '''"en": "Let's get started.",\n            "ja": "始めましょう。",\n            "focus": "get started",\n            "jaFocus": "始め",\n            "sentencePattern": "S + V + C",\n            "grammarParts": [\n              { "label": "S", "text": "we" },\n              { "label": "V", "text": "get" },\n              { "label": "C", "text": "started" }\n            ],\n            "grammarNote": "get started は「始まった状態になる」。Let's は Let us の短縮です。"''',
'''"en": "We should get started with the agenda.",\n            "ja": "議題から始めましょう。",\n            "focus": "get started",\n            "jaFocus": "始め"''': '''"en": "We should get started with the agenda.",\n            "ja": "私たちは議題から始めましょう。",\n            "focus": "get started",\n            "jaFocus": "始め",\n            "sentencePattern": "S + V + C + M",\n            "grammarParts": [\n              { "label": "S", "text": "We" },\n              { "label": "V", "text": "get" },\n              { "label": "C", "text": "started" },\n              { "label": "M", "text": "with the agenda" }\n            ]''',
'''"en": "Can we get started now?",\n            "ja": "今始めてもいいですか？",\n            "focus": "get started",\n            "jaFocus": "始め"''': '''"en": "Can we get started now?",\n            "ja": "私たちは今始めてもいいですか？",\n            "focus": "get started",\n            "jaFocus": "始め",\n            "sentencePattern": "S + V + C + M",\n            "grammarParts": [\n              { "label": "S", "text": "we" },\n              { "label": "V", "text": "get" },\n              { "label": "C", "text": "started" },\n              { "label": "M", "text": "now" }\n            ]''',
'''"en": "I got involved in this project last month.",\n            "ja": "先月このプロジェクトに関わるようになりました。",\n            "focus": "got involved",\n            "jaFocus": "関わる"''': '''"en": "I got involved in this project last month.",\n            "ja": "私は先月このプロジェクトに関わるようになりました。",\n            "focus": "got involved",\n            "jaFocus": "関わる",\n            "sentencePattern": "S + V + C + M",\n            "grammarParts": [\n              { "label": "S", "text": "I" },\n              { "label": "V", "text": "got" },\n              { "label": "C", "text": "involved" },\n              { "label": "M", "text": "in this project" }\n            ],\n            "grammarNote": "get involved in ... は「〜に関わるようになる」という自然なまとまりです。"''',
'''"en": "We need to get the sales team involved.",\n            "ja": "営業チームにも関わってもらう必要があります。",\n            "focus": "get involved",\n            "jaFocus": "関わって"''': '''"en": "We need to get the sales team involved.",\n            "ja": "私たちは営業チームにも関わってもらう必要があります。",\n            "focus": "get",\n            "object": "the sales team",\n            "jaFocus": "関わって",\n            "sentencePattern": "S + V + O + C",\n            "grammarParts": [\n              { "label": "S", "text": "We" },\n              { "label": "V", "text": "get" },\n              { "label": "O", "text": "the sales team" },\n              { "label": "C", "text": "involved" }\n            ]'''
}
for a,b in repls.items():
    if a in s:
        s=s.replace(a,b)
    else:
        print('not found',a[:60])
# attachPremiumDailyExamples: do not override existing; less awful generic fallback
s=s.replace('''    for (const phrase of [...verb.collocations, ...verb.phrasalVerbs]) {\n      phrase.dailyExamples = [\n        { en: `I often ${phrase.phrase} on weekends.`, ja: `週末によく「${phrase.ja}」という場面があります。`, focus: phrase.phrase, jaFocus: phrase.ja },\n        { en: `It's useful to know how to ${phrase.phrase}.`, ja: `「${phrase.ja}」の言い方を知っておくと便利です。`, focus: phrase.phrase, jaFocus: phrase.ja }\n      ];\n    }''','''    for (const phrase of [...verb.collocations, ...verb.phrasalVerbs]) {\n      if (phrase.dailyExamples && phrase.dailyExamples.length > 0) continue;\n      phrase.dailyExamples = [\n        { en: `I want to learn how to use \"${phrase.phrase}\" naturally.`, ja: `「${phrase.ja}」を自然に使えるようになりたいです。`, focus: phrase.phrase, jaFocus: phrase.ja },\n        { en: `This phrase is useful in everyday conversation.`, ja: `この表現は日常会話でも役立ちます。`, focus: phrase.phrase, jaFocus: "役立ちます" }\n      ];\n    }''')
p.write_text(s)
